name: 'Azure Pipeline' 
description: 'Trigger an Azure pipeline release' 
inputs:
  azure-devops-project-url:
    description: 'Fullyqualified URL to the Azure DevOps organization along with project name(eg, https://dev.azure.com/organization/project-name or https://server.example.com:8080/tfs/DefaultCollection/project-name)' 
    required: true 
  azure-pipeline-name:
    description: 'Name of the Azure Pipline to be triggered' 
    required: true 
  azure-devops-token: 
    description: 'Paste personal access token of the user as value of secret variable:AZURE_DEVOPS_TOKEN' 
    required: true 
runs: 
  using: 'node12' 
  main: 'lib/main.js' 