on:
  pull_request:    
    branches:
      - master
      - 'releases/*'
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci works properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm build
        npm test  